version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword

  server:
    build: .
    ports:
      - "8181:8181"
    depends_on:
      - db

  test:
    build: .
    command: npm run test
    depends_on:
      - server
