version: '3'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    networks:
      - app-network
  my-postgres:
    image: postgres:14.1-alpine
    container_name: my-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 25s
      retries: 3
  oms-back:
    image: oms-back
    container_name: oms-back
    networks:
      - app-network
    environment:
      - MONGO_CONNECTION_URI=mongodb://mongo-db:27017/test
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - SECRET_TOKEN_KEY=secretKey
      - PORT=8081
    depends_on:
      - my-postgres
  oms-back-test:
    image: oms-back-test
    container_name: oms-back-test
    networks:
      - app-network
    depends_on:
      - oms-back
networks:
  app-network:
    driver: bridge
volumes:
  pgdata: 
