version: '3'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    networks:
      - app-network

  my-postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - app-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                          
  oms-class3:
    image: oms-end3
    container_name: oms-class3
    networks:
      - app-network
    environment:
      - MONGO_CONNECTION_URI=mongodb://mongo-db:27017/test
      - DATABASE_USERNAME=postgresql://postgres:mypassword@my-postgres:5432/postgres
      - SECRET_TOKEN_KEY=secretKey
      - PORT=8081

  oms-test-class3:
    image: oms-end-test3
    container_name: oms--test-class3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
