version: '3'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    networks:
      - app-network

  my-postgres:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U postgres"]
      interval: 60s
      timeout: 60s
      retries: 5
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    #   - pg-data:/var/lib/postgresql/data
                          
  oms-class3:
    image: oms-end3
    container_name: oms-class3
    networks:
      - app-network
    environment:
      - MONGO_CONNECTION_URI=mongodb://mongo-db:27017/test
      - DATABASE_USERNAME=postgresql://postgres:mypassword@my-postgres:5432/postgres
      - SECRET_TOKEN_KEY=secretKey
      - PORT=8081
    depends_on:
      my-postgres:
        condition: service_healthy

  oms-test-class3:
    image: oms-end-test3
    container_name: oms--test-class3
    networks:
      - app-network
    depends_on:
      my-postgres:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

# volumes:
#   pg-data:
