version: '3'

services:
  test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"

  app:
    build: .
    command: npm start
    ports:
      - "your_preferred_port:your_application_port"
    depends_on:
      - test
