version: '3'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db
    networks:
      - app-network
  my-postgres:
    image: postgres
    container_name: my-postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    networks:
      - app-network
    volumes:
       - ./scripts:/docker-entrypoint-initdb.d
       - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 25s
      retries: 3
  oms-back:
    image: oms-back
    container_name: oms-back
    networks:
      - app-network
    environment:
      - MONGO_CONNECTION_URI=mongodb://mongo-db:27017/test
      - DATABASE_USERNAME=postgresql://postgres:mypassword@my-postgres:5432/db
      - SECRET_TOKEN_KEY=secretKey
      - PORT=8081
    depends_on:
      my-postgres:
        condition: service_healthy
  oms-back-test:
    image: oms-back-test
    container_name: oms-back-test
    networks:
      - app-network
    depends_on:
      oms-back:
        condition: service_started
networks:
  app-network:
    driver: bridge
# volumes:
#   pgdata: 
